/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.spidermanonlinefoodservicessofs;

import javax.swing.JOptionPane;
import com.mycompany.spidermanonlinefoodservicessofs.customer;
import com.mycompany.spidermanonlinefoodservicessofs.customerservice;

/**
 *
 * @author Alan Wong
 */
public class AddCustomer extends javax.swing.JFrame {
    
    private final customerservice customerservice;

    /**
     * Creates new form AddCustomer
     */
    public AddCustomer() {
        initComponents();
        this.customerservice = new customerservice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddCusLab = new javax.swing.JLabel();
        CusIDLab = new javax.swing.JLabel();
        CusUNLab = new javax.swing.JLabel();
        CusFNLab = new javax.swing.JLabel();
        CusEmailLab = new javax.swing.JLabel();
        CusPhoneLab = new javax.swing.JLabel();
        CusPassLab = new javax.swing.JLabel();
        CusIDTxt = new javax.swing.JTextField();
        CusUNTxt = new javax.swing.JTextField();
        CusFNTxt = new javax.swing.JTextField();
        CusEmailTxt = new javax.swing.JTextField();
        CusPhoneTxt = new javax.swing.JTextField();
        CusPassTxt = new javax.swing.JTextField();
        BackBut = new javax.swing.JButton();
        AddBut = new javax.swing.JButton();
        CusAddressLab = new javax.swing.JLabel();
        CusAddressTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AddCusLab.setBackground(new java.awt.Color(255, 255, 255));
        AddCusLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 36)); // NOI18N
        AddCusLab.setForeground(new java.awt.Color(0, 0, 0));
        AddCusLab.setText("Add Customer");

        CusIDLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        CusIDLab.setForeground(new java.awt.Color(0, 0, 0));
        CusIDLab.setText("Customer ID:");

        CusUNLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        CusUNLab.setForeground(new java.awt.Color(0, 0, 0));
        CusUNLab.setText("Customer Username:");

        CusFNLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        CusFNLab.setForeground(new java.awt.Color(0, 0, 0));
        CusFNLab.setText("Customer Full Name:");

        CusEmailLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        CusEmailLab.setForeground(new java.awt.Color(0, 0, 0));
        CusEmailLab.setText("Customer Emal:");

        CusPhoneLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        CusPhoneLab.setForeground(new java.awt.Color(0, 0, 0));
        CusPhoneLab.setText("Customer Phone:");

        CusPassLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        CusPassLab.setForeground(new java.awt.Color(0, 0, 0));
        CusPassLab.setText("Customer Password:");

        BackBut.setBackground(new java.awt.Color(255, 255, 255));
        BackBut.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        BackBut.setForeground(new java.awt.Color(0, 0, 0));
        BackBut.setText("Back");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        AddBut.setBackground(new java.awt.Color(255, 255, 255));
        AddBut.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        AddBut.setForeground(new java.awt.Color(0, 0, 0));
        AddBut.setText("Add");
        AddBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButActionPerformed(evt);
            }
        });

        CusAddressLab.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        CusAddressLab.setForeground(new java.awt.Color(0, 0, 0));
        CusAddressLab.setText("Customer Address:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(AddCusLab, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CusPassLab)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CusPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CusIDLab, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CusUNLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CusFNLab, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(CusEmailLab, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CusPhoneLab)
                                    .addComponent(CusAddressLab))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(CusIDTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                            .addComponent(CusUNTxt)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CusEmailTxt))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CusPhoneTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CusAddressTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CusFNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(BackBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AddBut)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(AddCusLab)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CusIDLab)
                    .addComponent(CusIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CusUNLab)
                    .addComponent(CusUNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CusFNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CusFNLab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CusEmailLab)
                    .addComponent(CusEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CusAddressLab)
                    .addComponent(CusAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CusPhoneLab)
                    .addComponent(CusPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CusPassLab)
                    .addComponent(CusPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBut)
                    .addComponent(AddBut))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButActionPerformed
        // TODO add your handling code here:
        String CusID = CusIDTxt.getText();
        String CusUN = CusUNTxt.getText();
        String CusFN = CusFNTxt.getText();
        String CusEmail = CusEmailTxt.getText();
        String CusPhone = CusPhoneTxt.getText();
        String CusAddress = CusAddressTxt.getText();
        String CusPass = CusPassTxt.getText();

        if (CusID.isEmpty() ||CusUN.isEmpty() || CusFN.isEmpty() || CusFN.isEmpty() || CusEmail.isEmpty() || CusPhone.isEmpty() || CusAddress.isEmpty() || CusPass.isEmpty()){
            JOptionPane.showMessageDialog(this, "Field(s) cannot be empty");
            return;
        }

        if (!CusPass.chars().allMatch(Character::isLetterOrDigit)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid password");
            return;
        }
        
        customer customer = new customer(CusID, CusUN, CusFN, CusEmail, CusPhone, CusAddress, CusPass);

        customerservice.create(customer);

        JOptionPane.showMessageDialog(this, "Customer has been added");

        // Reset input fields
        CusIDTxt.setText("");
        CusUNTxt.setText("");
        CusFNTxt.setText("");
        CusEmailTxt.setText("");
        CusPhoneTxt.setText("");
        CusAddressTxt.setText("");
        CusPassTxt.setText("");
    }//GEN-LAST:event_AddButActionPerformed

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        // TODO add your handling code here:
        AdminMainPage AP = new AdminMainPage();
        AP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBut;
    private javax.swing.JLabel AddCusLab;
    private javax.swing.JButton BackBut;
    private javax.swing.JLabel CusAddressLab;
    private javax.swing.JTextField CusAddressTxt;
    private javax.swing.JLabel CusEmailLab;
    private javax.swing.JTextField CusEmailTxt;
    private javax.swing.JLabel CusFNLab;
    private javax.swing.JTextField CusFNTxt;
    private javax.swing.JLabel CusIDLab;
    private javax.swing.JTextField CusIDTxt;
    private javax.swing.JLabel CusPassLab;
    private javax.swing.JTextField CusPassTxt;
    private javax.swing.JLabel CusPhoneLab;
    private javax.swing.JTextField CusPhoneTxt;
    private javax.swing.JLabel CusUNLab;
    private javax.swing.JTextField CusUNTxt;
    // End of variables declaration//GEN-END:variables
}
