/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.spidermanonlinefoodservicessofs;

/**
 *
 * @author Alan Wong
 */
public class AdminMainPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminMainPage
     */
    public AdminMainPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoutBut = new javax.swing.JButton();
        WelcomeAdminLab = new javax.swing.JLabel();
        AddFDItemBut = new javax.swing.JButton();
        ModifyFDItemBut = new javax.swing.JButton();
        ViewFDItemBut = new javax.swing.JButton();
        ViewCusOrderBut = new javax.swing.JButton();
        DltFDItemBut = new javax.swing.JButton();
        AddCusBut = new javax.swing.JButton();
        ModifyCusBut = new javax.swing.JButton();
        DltCusBut = new javax.swing.JButton();
        ViewAdminBut = new javax.swing.JButton();
        AddAdminBut = new javax.swing.JButton();
        ModifyAdminBut = new javax.swing.JButton();
        DltAdminBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LogoutBut.setBackground(new java.awt.Color(255, 255, 255));
        LogoutBut.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 14)); // NOI18N
        LogoutBut.setForeground(new java.awt.Color(0, 0, 0));
        LogoutBut.setText("Logout");
        LogoutBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButActionPerformed(evt);
            }
        });

        WelcomeAdminLab.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        WelcomeAdminLab.setForeground(new java.awt.Color(0, 0, 0));
        WelcomeAdminLab.setText("Welcome Back Admin");

        AddFDItemBut.setBackground(new java.awt.Color(255, 255, 255));
        AddFDItemBut.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        AddFDItemBut.setForeground(new java.awt.Color(0, 0, 0));
        AddFDItemBut.setText("Add Food items");
        AddFDItemBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFDItemButActionPerformed(evt);
            }
        });

        ModifyFDItemBut.setBackground(new java.awt.Color(255, 255, 255));
        ModifyFDItemBut.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        ModifyFDItemBut.setForeground(new java.awt.Color(0, 0, 0));
        ModifyFDItemBut.setText("Modify Food Item");
        ModifyFDItemBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyFDItemButActionPerformed(evt);
            }
        });

        ViewFDItemBut.setBackground(new java.awt.Color(255, 255, 255));
        ViewFDItemBut.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        ViewFDItemBut.setForeground(new java.awt.Color(0, 0, 0));
        ViewFDItemBut.setText("View Food item");
        ViewFDItemBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewFDItemButActionPerformed(evt);
            }
        });

        ViewCusOrderBut.setBackground(new java.awt.Color(255, 255, 255));
        ViewCusOrderBut.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        ViewCusOrderBut.setForeground(new java.awt.Color(0, 0, 0));
        ViewCusOrderBut.setText("View Order");
        ViewCusOrderBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewCusOrderButActionPerformed(evt);
            }
        });

        DltFDItemBut.setBackground(new java.awt.Color(255, 255, 255));
        DltFDItemBut.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        DltFDItemBut.setForeground(new java.awt.Color(0, 0, 0));
        DltFDItemBut.setText("Deleted Food Item");
        DltFDItemBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DltFDItemButActionPerformed(evt);
            }
        });

        AddCusBut.setBackground(new java.awt.Color(255, 255, 255));
        AddCusBut.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        AddCusBut.setForeground(new java.awt.Color(0, 0, 0));
        AddCusBut.setText("Add Customer");
        AddCusBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCusButActionPerformed(evt);
            }
        });

        ModifyCusBut.setBackground(new java.awt.Color(255, 255, 255));
        ModifyCusBut.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        ModifyCusBut.setForeground(new java.awt.Color(0, 0, 0));
        ModifyCusBut.setText("Modify Customer");
        ModifyCusBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyCusButActionPerformed(evt);
            }
        });

        DltCusBut.setBackground(new java.awt.Color(255, 255, 255));
        DltCusBut.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        DltCusBut.setForeground(new java.awt.Color(0, 0, 0));
        DltCusBut.setText("Deleted Customer");
        DltCusBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DltCusButActionPerformed(evt);
            }
        });

        ViewAdminBut.setBackground(new java.awt.Color(255, 255, 255));
        ViewAdminBut.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        ViewAdminBut.setForeground(new java.awt.Color(0, 0, 0));
        ViewAdminBut.setText("View Admin");
        ViewAdminBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAdminButActionPerformed(evt);
            }
        });

        AddAdminBut.setBackground(new java.awt.Color(255, 255, 255));
        AddAdminBut.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        AddAdminBut.setForeground(new java.awt.Color(0, 0, 0));
        AddAdminBut.setText("Add Admin");
        AddAdminBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddAdminButActionPerformed(evt);
            }
        });

        ModifyAdminBut.setBackground(new java.awt.Color(255, 255, 255));
        ModifyAdminBut.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        ModifyAdminBut.setForeground(new java.awt.Color(0, 0, 0));
        ModifyAdminBut.setText("Modify Admin");
        ModifyAdminBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyAdminButActionPerformed(evt);
            }
        });

        DltAdminBut.setBackground(new java.awt.Color(255, 255, 255));
        DltAdminBut.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        DltAdminBut.setForeground(new java.awt.Color(0, 0, 0));
        DltAdminBut.setText("Deleted Admin");
        DltAdminBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DltAdminButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WelcomeAdminLab, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(186, 186, 186))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LogoutBut)
                        .addGap(27, 27, 27))))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddFDItemBut, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ViewFDItemBut, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModifyFDItemBut, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DltFDItemBut, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddCusBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifyCusBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DltCusBut, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                    .addComponent(ViewCusOrderBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ViewAdminBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddAdminBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModifyAdminBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DltAdminBut, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(WelcomeAdminLab)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ViewFDItemBut)
                    .addComponent(ViewCusOrderBut)
                    .addComponent(ViewAdminBut))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddFDItemBut)
                    .addComponent(AddCusBut)
                    .addComponent(AddAdminBut))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModifyCusBut)
                    .addComponent(ModifyFDItemBut)
                    .addComponent(ModifyAdminBut))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DltCusBut)
                    .addComponent(DltFDItemBut)
                    .addComponent(DltAdminBut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(LogoutBut)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddFDItemButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFDItemButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddFoodItem().setVisible(true);
    }//GEN-LAST:event_AddFDItemButActionPerformed

    private void ModifyFDItemButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyFDItemButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ModifyFood().setVisible(true);
    }//GEN-LAST:event_ModifyFDItemButActionPerformed

    private void ViewFDItemButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewFDItemButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewFood().setVisible(true);
    }//GEN-LAST:event_ViewFDItemButActionPerformed

    private void ViewCusOrderButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewCusOrderButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewCustomerOrder().setVisible(true);
    }//GEN-LAST:event_ViewCusOrderButActionPerformed

    private void LogoutButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_LogoutButActionPerformed

    private void DltFDItemButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DltFDItemButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DeleteFood().setVisible(true);
    }//GEN-LAST:event_DltFDItemButActionPerformed

    private void ModifyCusButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyCusButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ModifyCustomer().setVisible(true);
    }//GEN-LAST:event_ModifyCusButActionPerformed

    private void AddCusButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCusButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddCustomer().setVisible(true);
    }//GEN-LAST:event_AddCusButActionPerformed

    private void DltCusButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DltCusButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DeleteCustomer().setVisible(true);
    }//GEN-LAST:event_DltCusButActionPerformed

    private void ViewAdminButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAdminButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ViewAdmin().setVisible(true);
    }//GEN-LAST:event_ViewAdminButActionPerformed

    private void AddAdminButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddAdminButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new AddAdmin().setVisible(true);
    }//GEN-LAST:event_AddAdminButActionPerformed

    private void ModifyAdminButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyAdminButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ModifyAdmin().setVisible(true);
    }//GEN-LAST:event_ModifyAdminButActionPerformed

    private void DltAdminButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DltAdminButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new DeleteAdmin().setVisible(true);
    }//GEN-LAST:event_DltAdminButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddAdminBut;
    private javax.swing.JButton AddCusBut;
    private javax.swing.JButton AddFDItemBut;
    private javax.swing.JButton DltAdminBut;
    private javax.swing.JButton DltCusBut;
    private javax.swing.JButton DltFDItemBut;
    private javax.swing.JButton LogoutBut;
    private javax.swing.JButton ModifyAdminBut;
    private javax.swing.JButton ModifyCusBut;
    private javax.swing.JButton ModifyFDItemBut;
    private javax.swing.JButton ViewAdminBut;
    private javax.swing.JButton ViewCusOrderBut;
    private javax.swing.JButton ViewFDItemBut;
    private javax.swing.JLabel WelcomeAdminLab;
    // End of variables declaration//GEN-END:variables
}
