/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.spidermanonlinefoodservicessofs;

import javax.swing.JOptionPane;
import com.mycompany.spidermanonlinefoodservicessofs.customer;
import com.mycompany.spidermanonlinefoodservicessofs.customerservice;

/**
 *
 * @author Alan Wong
 */
public class ModifyCustomer extends javax.swing.JFrame {
    
    private final customerservice customerservice;

    /**
     * Creates new form ModifyCustomer
     */
    public ModifyCustomer() {
        initComponents();
        this.customerservice = new customerservice();
        performFileRelatedTask();
    }
    
    private void performFileRelatedTask() {
        StringBuilder stringBuilder = new StringBuilder();
        
        customerservice.getAll().forEach((customer) -> {
            stringBuilder.append(customer.getCusID())
                    .append("\t")
                    .append(customer.getCusUN())
                    .append("\t")
                    .append(customer.getCusFN())
                    .append("\t")
                    .append(customer.getCusEmail())
                    .append("\t")
                    .append(customer.getCusPhone())
                    .append("\t")
                    .append(customer.getCusAddress())
                    .append("\t")
                    .append(customer.getCusPass())
                    .append("\n");
        });
        ModifyCusTxt.setText(stringBuilder.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ModifyCusLab = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ModifyCusTxt = new javax.swing.JTextArea();
        OldCusIDLab = new javax.swing.JLabel();
        NUNLab = new javax.swing.JLabel();
        NFNLab = new javax.swing.JLabel();
        NEmailLab = new javax.swing.JLabel();
        NPhoneLab = new javax.swing.JLabel();
        NAddressLab = new javax.swing.JLabel();
        oldCusIDTxt = new javax.swing.JTextField();
        newCusUNTxt = new javax.swing.JTextField();
        newCusFNTxt = new javax.swing.JTextField();
        newCusEmailTxt = new javax.swing.JTextField();
        newCusPhoneTxt = new javax.swing.JTextField();
        newCusAddressTxt = new javax.swing.JTextField();
        BackBut = new javax.swing.JButton();
        ModifyBut = new javax.swing.JButton();
        NPassLab = new javax.swing.JLabel();
        newCusPassTxt = new javax.swing.JTextField();
        NCusIDLab = new javax.swing.JLabel();
        newCusIDTxt = new javax.swing.JTextField();

        jTextField1.setText("jTextField1");

        jTextField2.setText("jTextField2");

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ModifyCusLab.setBackground(new java.awt.Color(255, 255, 255));
        ModifyCusLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 24)); // NOI18N
        ModifyCusLab.setForeground(new java.awt.Color(0, 0, 0));
        ModifyCusLab.setText("Modify Customer");

        ModifyCusTxt.setColumns(20);
        ModifyCusTxt.setRows(5);
        jScrollPane1.setViewportView(ModifyCusTxt);

        OldCusIDLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        OldCusIDLab.setForeground(new java.awt.Color(0, 0, 0));
        OldCusIDLab.setText("Old Customer ID:");

        NUNLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        NUNLab.setForeground(new java.awt.Color(0, 0, 0));
        NUNLab.setText("Enter new Username:");

        NFNLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        NFNLab.setForeground(new java.awt.Color(0, 0, 0));
        NFNLab.setText("Enter new Fullname:");

        NEmailLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        NEmailLab.setForeground(new java.awt.Color(0, 0, 0));
        NEmailLab.setText("Enter new Email:");

        NPhoneLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        NPhoneLab.setForeground(new java.awt.Color(0, 0, 0));
        NPhoneLab.setText("Enter new Phone:");

        NAddressLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        NAddressLab.setForeground(new java.awt.Color(0, 0, 0));
        NAddressLab.setText("Enter new Address:");

        BackBut.setBackground(new java.awt.Color(255, 255, 255));
        BackBut.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        BackBut.setForeground(new java.awt.Color(0, 0, 0));
        BackBut.setText("Back");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        ModifyBut.setBackground(new java.awt.Color(255, 255, 255));
        ModifyBut.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        ModifyBut.setForeground(new java.awt.Color(0, 0, 0));
        ModifyBut.setText("Modify");
        ModifyBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModifyButActionPerformed(evt);
            }
        });

        NPassLab.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        NPassLab.setForeground(new java.awt.Color(0, 0, 0));
        NPassLab.setText("Enter new Password:");

        NCusIDLab.setFont(new java.awt.Font("Yu Gothic UI Semilight", 3, 18)); // NOI18N
        NCusIDLab.setForeground(new java.awt.Color(0, 0, 0));
        NCusIDLab.setText("Enter New ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ModifyCusLab, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(BackBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ModifyBut)
                .addGap(68, 68, 68))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OldCusIDLab, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(NFNLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NUNLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                                .addComponent(NAddressLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(NEmailLab)
                            .addComponent(NPhoneLab)
                            .addComponent(NPassLab, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NCusIDLab, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newCusUNTxt)
                            .addComponent(newCusFNTxt, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(oldCusIDTxt)
                            .addComponent(newCusEmailTxt)
                            .addComponent(newCusPhoneTxt)
                            .addComponent(newCusAddressTxt)
                            .addComponent(newCusPassTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                            .addComponent(newCusIDTxt))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(ModifyCusLab)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OldCusIDLab)
                    .addComponent(oldCusIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NCusIDLab)
                    .addComponent(newCusIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUNLab)
                    .addComponent(newCusUNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NFNLab)
                    .addComponent(newCusFNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NEmailLab)
                    .addComponent(newCusEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NPhoneLab)
                    .addComponent(newCusPhoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAddressLab)
                    .addComponent(newCusAddressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NPassLab)
                    .addComponent(newCusPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBut)
                    .addComponent(ModifyBut))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        // TODO add your handling code here:
        AdminMainPage AP = new AdminMainPage();
        AP.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButActionPerformed

    private void ModifyButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModifyButActionPerformed
        // TODO add your handling code here:
        String sourceCusID = oldCusIDTxt.getText();
        String CusID = newCusIDTxt.getText();
        String CusUN = newCusUNTxt.getText();
        String CusFN = newCusFNTxt.getText();
        String CusEmail = newCusEmailTxt.getText();
        String CusPhone = newCusPhoneTxt.getText();
        String CusAddress = newCusAddressTxt.getText();
        String CusPass = newCusPassTxt.getText();
        
        if (sourceCusID.isEmpty() || CusID.isEmpty() || CusFN.isEmpty() || CusFN.isEmpty() || CusEmail.isEmpty() || CusPhone.isEmpty() || CusAddress.isEmpty() || CusPass.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Fields cannot be left empty");
            return;
        }

        if (!newCusPassTxt.getText().chars().allMatch(Character::isLetterOrDigit)) {
            JOptionPane.showMessageDialog(this, "Please enter valid password");
            return;
        }

        customer ModifyCustomer = new customer(CusID, CusUN, CusFN, CusEmail, CusPhone, CusAddress, CusPass);

        boolean isUpdated = customerservice.update(sourceCusID, ModifyCustomer);
        
        if (!isUpdated) {
            JOptionPane.showConfirmDialog(this, "No customer found to update");
            return;
        }

        // Reset the modify fields
        oldCusIDTxt.setText("");
        newCusIDTxt.setText("");
        newCusUNTxt.setText("");
        newCusFNTxt.setText("");
        newCusEmailTxt.setText("");
        newCusPhoneTxt.setText("");
        newCusAddressTxt.setText("");
        newCusPassTxt.setText("");

        // Show confirmation pop up
        JOptionPane.showMessageDialog(this, "Customer infomation has been Updated");

        // Update display information
        performFileRelatedTask();

    }//GEN-LAST:event_ModifyButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JButton ModifyBut;
    private javax.swing.JLabel ModifyCusLab;
    private javax.swing.JTextArea ModifyCusTxt;
    private javax.swing.JLabel NAddressLab;
    private javax.swing.JLabel NCusIDLab;
    private javax.swing.JLabel NEmailLab;
    private javax.swing.JLabel NFNLab;
    private javax.swing.JLabel NPassLab;
    private javax.swing.JLabel NPhoneLab;
    private javax.swing.JLabel NUNLab;
    private javax.swing.JLabel OldCusIDLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField newCusAddressTxt;
    private javax.swing.JTextField newCusEmailTxt;
    private javax.swing.JTextField newCusFNTxt;
    private javax.swing.JTextField newCusIDTxt;
    private javax.swing.JTextField newCusPassTxt;
    private javax.swing.JTextField newCusPhoneTxt;
    private javax.swing.JTextField newCusUNTxt;
    private javax.swing.JTextField oldCusIDTxt;
    // End of variables declaration//GEN-END:variables
}
