/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.spidermanonlinefoodservicessofs;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JOptionPane;
import com.mycompany.spidermanonlinefoodservicessofs.admin;
import com.mycompany.spidermanonlinefoodservicessofs.adminservice;

/**
 *
 * @author Alan Wong
 */
public class RegisterAdmin extends javax.swing.JFrame {
    
    private final adminservice adminservice;

    /**
     * Creates new form RegisterAdminPage
     */
    public RegisterAdmin() {
        initComponents();
        this.adminservice = new adminservice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StaffPageLab = new javax.swing.JLabel();
        StaffUNLab = new javax.swing.JLabel();
        StaffPassLab = new javax.swing.JLabel();
        StaffUNTxt = new javax.swing.JTextField();
        StaffPassTxt = new javax.swing.JTextField();
        BackBut = new javax.swing.JButton();
        ClearBut = new javax.swing.JButton();
        RegisterBut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        StaffPageLab.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 36)); // NOI18N
        StaffPageLab.setForeground(new java.awt.Color(255, 51, 51));
        StaffPageLab.setText("Staff Registertation Page");

        StaffUNLab.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        StaffUNLab.setForeground(new java.awt.Color(0, 0, 0));
        StaffUNLab.setText("Staff Username:");

        StaffPassLab.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        StaffPassLab.setForeground(new java.awt.Color(0, 0, 0));
        StaffPassLab.setText("Staff Password:");

        BackBut.setBackground(new java.awt.Color(255, 255, 255));
        BackBut.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        BackBut.setForeground(new java.awt.Color(0, 0, 0));
        BackBut.setText("Back");
        BackBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButActionPerformed(evt);
            }
        });

        ClearBut.setBackground(new java.awt.Color(255, 255, 255));
        ClearBut.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        ClearBut.setForeground(new java.awt.Color(0, 0, 0));
        ClearBut.setText("Clear");
        ClearBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButActionPerformed(evt);
            }
        });

        RegisterBut.setBackground(new java.awt.Color(255, 255, 255));
        RegisterBut.setFont(new java.awt.Font("Yu Gothic UI Semibold", 3, 18)); // NOI18N
        RegisterBut.setForeground(new java.awt.Color(0, 0, 0));
        RegisterBut.setText("Register");
        RegisterBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StaffPageLab, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StaffPassLab, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(StaffUNLab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(StaffUNTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .addComponent(StaffPassTxt))))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(BackBut)
                .addGap(69, 69, 69)
                .addComponent(ClearBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegisterBut)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(StaffPageLab)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffUNLab)
                    .addComponent(StaffUNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StaffPassLab)
                    .addComponent(StaffPassTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackBut)
                    .addComponent(ClearBut)
                    .addComponent(RegisterBut))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new LoginAdmin().setVisible(true);
    }//GEN-LAST:event_BackButActionPerformed

    private void ClearButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButActionPerformed
        // TODO add your handling code here:
        StaffUNTxt.setText("");
        StaffPassTxt.setText("");
    }//GEN-LAST:event_ClearButActionPerformed

    private void RegisterButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButActionPerformed
        // TODO add your handling code here:
        String StaffUN = StaffUNTxt.getText().trim();
        String StaffPass = StaffPassTxt.getText().trim();
        
        try{
                FileWriter fr = new FileWriter("storage/staff.txt",true);
                try(PrintWriter pr = new PrintWriter(fr)){
                    pr.println(StaffUN + "," + StaffPass);
                    admin admin = new admin(StaffUN, StaffPass);
                    adminservice.create(admin);
                    JOptionPane.showMessageDialog(this, "Account Success Register!");
                    
                    
                }
            }   catch (IOException e){
            }
            this.setVisible(false);
            new LoginAdmin().setVisible(true);
    }//GEN-LAST:event_RegisterButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBut;
    private javax.swing.JButton ClearBut;
    private javax.swing.JButton RegisterBut;
    private javax.swing.JLabel StaffPageLab;
    private javax.swing.JLabel StaffPassLab;
    private javax.swing.JTextField StaffPassTxt;
    private javax.swing.JLabel StaffUNLab;
    private javax.swing.JTextField StaffUNTxt;
    // End of variables declaration//GEN-END:variables
}
